title = "ToolChest Pro"
baseURL = "https://toolchest.pro/"
languageCode = "en-us"
theme = "m10c"

enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

# Pagination
paginate = 10
paginatePath = "page"

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"

# Markup settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    lineNumbersInTable = false
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# Site parameters
[params]
  description = "Anti-overwhelm business tool curation platform with expert-backed recommendations to help you find the right tools without the research fatigue"
  author = "ToolChest Pro"
  recent_posts_number = 10
  show_reading_time = true
  background_color_class = "bg-black"
  featured_image = "/images/site-feature-image.jpg"
  
  # Logo and branding
  avatar = "/images/toolchest-logo.svg"
  
  # ToolChest Pro Color Scheme
  [params.style]
    darkestColor = "#2E3A46"     # Deep iron gray background
    darkColor = "#444444"        # Card background (slightly lighter)
    lightColor = "#9EC9FF"       # Pale blue accent text for headings
    lightestColor = "#FFFFFF"    # Pure white primary text
    primaryColor = "#E74C3C"     # Bold red for CTA/buttons
  
  # Social media
  [params.social]
    twitter = "toolchestpro"
    github = "toolchestpro"

# Menu configuration
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 20

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 30

# Privacy configuration
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = false
    anonymizeIP = true
    respectDoNotTrack = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = false
    enableDNT = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true